### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by maelle** [ropensci/rWBclimate#35]
Has development of this package been suspended? In that case, I'd add a suspended badge and archive it (= make it read-only, which is reversible)

**Comment by sckott** [comment]
@emhart if  you like we can take over maintenance. thoughrts?

**Comment by emhart** [comment]
Sure, the code is probably quite dated by now, not sure if it warrants  a full refactorization, or just should be archived.  What maintenance did you have in mind @sckott ?

**Comment by sckott** [comment]
just at few small things: the last update on cran was 4 years ago, readme needs updating since it is on cran, but install instructions say only install from github

internals may be totally fine, haven't really looked at them

Does the package still work for the most part?

**Comment by ibarraespinosa** [comment]
Hi, i love this package. Best, Sergio

**Comment by maelle** [comment]
This package is about to be archived cf discussion in https://github.com/ropensci/rWBclimate/issues/47

Please contact `info@ropensci.org` if you have any question or want to revive the package.
