### ISSUE TITLE
get_ensemble_temp does not work!

### ISSUE THREAD

**Issue by mshariful** [ropensci/rWBclimate#36]
Hello,
I am simply trying to follow the tutorial at https://ropensci.org/usecases/rwbclimate_plotting/

When I execute 
`dat <- get_ensemble_temp("GBR", "annualavg", 1900, 2100)`
I get the following error:

> No encoding supplied: defaulting to UTF-8.
Error in rep("past", dim(data_out)[1]) : invalid 'times' argument

Could you please help. Thanks, Sharif

**Comment by salvatirehbein** [comment]
just install the github version

`
remotes::install_github("ropensci/rWBclimate")`

https://github.com/ropensci/rWBclimate/commit/5ce58a98b5579dc8f2e7ccd47fea5a1053b95ef6
