### ISSUE TITLE
temp_dat gives No encoding supplied error?

### ISSUE THREAD

**Issue by danief** [ropensci/rWBclimate#37]
country <- c("NOR", "USA", "ESP")
temp_dat <- get_model_temp(country, "annualavg", 1950, 2050)

**No encoding supplied: defaulting to UTF-8.
Error in rep("past", dim(data_out)[1]) : invalid 'times' argument**

**Comment by emhart** [comment]
Hmmmm, I'll have to look into this.  Someone also recently sent me this bug.  Let me see if I can get a basic fix up.

**Comment by dokato** [comment]
+1 I'm having the same issue ( R version 3.5.1 and the most recent version of the package)

**Comment by tanerumit** [comment]
Yes, same here. Functions no longer work

**Comment by sckott** [comment]
have time to look into this yet @emhart ?

**Comment by makbuk** [comment]
Have the same issue. 
R version 3.6.1, rWBclimate version 0.1.3

gbr.dat.t <- get_ensemble_temp("GBR", "annualavg", 1900, 2100)
**No encoding supplied: defaulting to UTF-8.
Error in rep("past", dim(data_out)[1]) : invalid 'times' argument**

**Comment by Ghanshyamsavaliya** [comment]
@emhart , @sckott,  Do we have any update on it?

Because I am still facing similar kind of issue.

**Comment by sckott** [comment]
fixed that error so it checks the http status first, which reveals that the API this pkg uses is completely gone. the package needs a re-write for sure

**Comment by joda70** [comment]
Any news for this problem?

**Comment by FONDECYTACC** [comment]
The problem persist until today

**Comment by salvatirehbein** [comment]
We're working to solve this.

**Comment by karigar** [comment]
Any update please

**Comment by salvatirehbein** [comment]
The package was updated on Github and the encoding problem was fixed as well. So, please install the package using remotes, this should solve the problem by now:

remotes::install_github("ropensci/rWBclimate")

The CRAN version will be updated next year, where we will include CMIP5 (and hopefully 6) data.

**Comment by karigar** [comment]
Thank and appreciate it.
Shahid
