### ISSUE TITLE
Any plans for CMIP5 data sets?

### ISSUE THREAD

**Issue by AmeerDotHydro** [ropensci/rWBclimate#42]
Hello, 
I recently came to know about this package- great package. I just wanted to know if there are any plans to update the package by including CMIP5 models data? I guess it would be hard to defend using AR4 data set for research/publication purposes, knowing that improvement has been made to models that produces these future climate projections.
Thank you,
Ameer

**Comment by sckott** [comment]
@ibarraespinosa any thoughts on this?

**Comment by salvatirehbein** [comment]
Hi @AmeerDotHydro,

Thanks for your enquire. The challenge here is that the different protocols have distinct APIs and data format access. Nevertheless, @ibarraespinosa and I are working to implement that. Once it is implemented, this issue will be closed.

Best,
Amanda

**Comment by AmeerDotHydro** [comment]
Great- thanks for looking into this @salvatirehbein. I look forward to using the updated package when ready. Any approximate timeline for completing this task?
Regards,
Ameer

**Comment by AmeerDotHydro** [comment]
@salvatirehbein @sckott - any update?

**Comment by maelle** [comment]
This package is about to be archived cf discussion in https://github.com/ropensci/rWBclimate/issues/47

Please contact `info@ropensci.org` if you have any question or want to revive the package.
