### ISSUE TITLE
Example does not work anymore

### ISSUE THREAD

**Issue by alishersuyunov** [ropensci/rWBclimate#44]
The example code as presented below, does not work anymore:
`af_basin <- create_map_df(Africa_basin)`

It is throwing a following error message: 
> Error in create_map_df(Africa_basin) : 
> A map file for  379 contains no data, please set the resolution parameter closer to 0 or remove it from your list of maps to download

KML files contain only NULL values:
`<kml><Document><Placemark><name>385</name>null</Placemark></Document></kml>`

**Comment by maelle** [comment]
This package is about to be archived cf discussion in https://github.com/ropensci/rWBclimate/issues/47

Please contact `info@ropensci.org` if you have any question or want to revive the package.
