### ISSUE TITLE
Bug with `get_ensemble_stats()`

### ISSUE THREAD

**Issue by choisy** [ropensci/rWBclimate#45]
When I type the following command
```
ens_dat <- get_ensemble_stats("USA","mavg","ppt_days2")
```
from the help of the `get_ensemble_stats()` function, I get this error message:
```
No encoding supplied: defaulting to UTF-8.
Error in `$<-.data.frame`(`*tmp*`, "fromYear", value = c(2046, 2046, 2046,  : 
  replacement has 12 rows, data has 0
```
Any idea of what is going on?

**Comment by maelle** [comment]
This package is about to be archived cf discussion in https://github.com/ropensci/rWBclimate/issues/47

Please contact `info@ropensci.org` if you have any question or want to revive the package.
