### ISSUE TITLE
Action needed before 2023-01-25: update rWBclimate's dependencies as it cannot be built

### ISSUE THREAD

**Issue by maelle** [ropensci/rWBclimate#47]
:wave: @emhart!

Your rWBclimate package cannot be built on R-universe as it depends on the deprecated spatial package rgdal. See for instance this [write up by Jakub Nowosad to understand the changes in the R spatial ecosystem](https://geocompx.org/post/2023/rgdal-retirement/index.html). :world_map: 

**Please indicate us before January, the 25th whether you intend to update your package.** If not, we will archive rWBclimate* and remove it from rOpenSci registry. You do not need to make changes before January, the 25th; but you do need to drop us a line before then.

You can find [help](https://devdevguide.netlify.app/maintenance_cheatsheet), among other places, in our Slack's workspace "spatial" and "package-maintenance" channels.

Thank you! :pray:

*: We can unarchive the repository and transfer it to your own account, at your request. We won't shred it. :smile_cat: 

@ropensci/admin

**Comment by maelle** [comment]
Reminder sent per email.

**Comment by ibarraespinosa** [comment]
hi, I'm going to help with this. This package it is really outdated tho, because it provides access to data AR4 and how we are in SSP scenarios. I have not been able to find a API to connect with more updated data

**Comment by maelle** [comment]
Thank you @ibarraespinosa! Do you need/want an invitation to rOpenSci slack workspace? If so, could you please indicate at which email address (here or via `maelle@ropensci.org`)?

**Comment by ibarraespinosa** [comment]
zergioibarra@gmail.com

**Comment by maelle** [comment]
Invite sent, sorry for the delay! See you soon in Slack!

**Comment by maelle** [comment]
:wave: @ibarraespinosa  I see all builds are failing on https://ropensci.r-universe.dev/builds. Any update, any help needed? 

cc @ropensci/admin

**Comment by ibarraespinosa** [comment]
Hi Markle,

The last time I checked, there was no new API available from world Bank. I
will check again and let you know.

Best regards

**Comment by maelle** [comment]
:wave: @ibarraespinosa any update? Should we actually archive this package then?

cc  @ropensci/admin @jeroen

**Comment by jeroen** [comment]
Let's archive it, we can unarchive if somebody wants to pick it up.

**Comment by maelle** [comment]
This package is about to be archived cf discussion in https://github.com/ropensci/rWBclimate/issues/47

Please contact `info@ropensci.org` if you have any question or want to revive the package.
